### ISSUE TITLE
Getting an error with bs4.FeatureNotFound on WSL 

### ISSUE THREAD

**Issue by kalyan860** [rocktimsaikia/cambd-cli#17]
raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by rocktimsaikia** [comment]
It's using `html5lib` for parsing. Can you check if it is already installed or not?

```sh
pip show html5lib
```
If not can you install it? and try again?

**Comment by kalyan860** [comment]
works now, thanks.
Maybe you could add this library to requirements.txt

**Comment by rocktimsaikia** [comment]
Just added it. The requirements.txt was autogenerated initially and `html5lib` lib is not being directly imported so it was not added there automatically.
