### ISSUE TITLE
Error when use word 'substitute'

### ISSUE THREAD

**Issue by xerenahmed** [rocktimsaikia/cambd-cli#27]
```
cambd.py", line 85, in get_definitions
    definition = dcon.find(attrs={"class": "ddef_d"}).get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by xerenahmed** [comment]
Also with 'urgent'

**Comment by rocktimsaikia** [comment]
The recent changes in #26 might have caused this. Can you look into this?

The live version shows definition for both `substitute` and `urgent` just fine.
![image](https://user-images.githubusercontent.com/33410545/204130375-b119bb8a-d111-4c7b-ba29-301c726273b1.png)

**Comment by xerenahmed** [comment]
I tried with #26, this happens or some words. I'll reproduce the issue when I'm free.
